### ISSUE TITLE
General error: 1364 Field 'email' doesn't have a default value

### ISSUE THREAD

**Issue by loic-lopez** [scriptburn/git-auto-deploy#1]
Hi, i tried to install your project but i got this error:

`Unable to connect to db:SQLSTATE[HY000]: General error: 1364 Field 'email' doesn't have a default value`

**Comment by scriptburn** [comment]
Did you followed the install instruction ? because i just checked again in fresh install and i did not see any issue, Can you provide more detail that when you see the error , What were you doing ?

**Comment by loic-lopez** [comment]
i have run composer install and modified the app/settings file.

I am currently using mysql-community-server 5.7.

**Comment by scriptburn** [comment]
what is your document root?

**Comment by loic-lopez** [comment]
/root/git-auto-deploy/public

**Comment by scriptburn** [comment]
you must install by this command
`composer create-project --no-interaction scriptburn/git-auto-deploy my-app`

**Comment by loic-lopez** [comment]
same error but tables in database have been created but nothing is in the tables

**Comment by scriptburn** [comment]
if you still see this error can you open app/dependencies.php and change 
``
`username` varchar(255)  NULL,
  `email` varchar(255) NOT NULL,
  `role` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
``

to

``
`username` varchar(255)  NULL,
  `email` varchar(255) NULL,
  `role` varchar(255) NULL,
  `password` varchar(255) NOT NULL
``

**Comment by loic-lopez** [comment]
Ok after fix a sql error : ONLY_FULL_GROUP_BY it works !

**Comment by scriptburn** [comment]
I have no idea about your development or production environment but i am using mysql 5.6 on MAMP and never saw any of the DB issue you mentioned above. I wish i could regenerate them on my Dev environment so i can look into and fix them

**Comment by loic-lopez** [comment]
There have been a lot of changes with mysql 5.7

**Comment by scriptburn** [comment]
I think then i have to wait for MAMP to update there packaged mysql to ver 5.7
Also if you could post your exact solution here that would be helpful  for someone else too

**Comment by loic-lopez** [comment]
fix ONLY_FULL_GROUP_BY : 
`SET @@GLOBAL.sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";`

**Comment by loic-lopez** [comment]
Oh! while creating a project : 
`General error: 1364 Field 'last_hook_status' doesn't have a default value`

**Comment by scriptburn** [comment]
Can you test with one thing? First delete all tables in your db and then  
replace in app/dependencies.php
``$pdo          = new \Slim\PDO\Database($dsn, $c->settings['db']['user'], $c->settings['db']['pass']);``
with
``
        $pdo          = new \Slim\PDO\Database($dsn, $c->settings['db']['user'], $c->settings['db']['pass'],array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET sql_mode="TRADITIONAL"') );
``
And let me know how it goes so i can include these changes in next release

**Comment by loic-lopez** [comment]
i changed : 
 `last_hook_status` int(1) NOT NULL,

  `last_hook_time` datetime NOT NULL ,
  `last_hook_duration` int(5) NOT NULL,
  `last_hook_log` text NOT NULL,
    `composer_update` int(1) NOT NULL

to : 
 `last_hook_status` int(1) NULL,

  `last_hook_time` datetime NULL ,
  `last_hook_duration` int(5) NULL,
  `last_hook_log` text NULL,
    `composer_update` int(1) NULL

**Comment by scriptburn** [comment]
can you make change as requested in my last comment and see if everything is working

**Comment by loic-lopez** [comment]
I need to retablish the `last_hook_status` to its initial value ?

**Comment by scriptburn** [comment]
last_hook_status can have null too so just leave it as it is

**Comment by loic-lopez** [comment]
yes, i think  
`$pdo = new \Slim\PDO\Database($dsn, $c->settings['db']['user'], $c->settings['db']['pass'],array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET sql_mode="TRADITIONAL"') );` 
will work on the most systems
