### ISSUE TITLE
Trying to configure this in 2020

### ISSUE THREAD

**Issue by Skormie** [scriptburn/git-auto-deploy#19]
There were a few deprecated dependencies I had to get past but I managed. Now I'm getting this... It shows that the request failed but the response was 200.

Github is getting this response.
`{"status":0,"message":"Unknown remote branch"}`

My branch is master so I'm not sure why it wouldn't work... Do I need a local branch maybe?

**Comment by Hugobert** [comment]
I'm getting the same error. Did you solve the issue? If so, how?
