### ISSUE TITLE
The requested URL /login was not found on this server.

### ISSUE THREAD

**Issue by chizuoka** [scriptburn/git-auto-deploy#3]
I had my domain point to the /public folder ... but i got a 404. May i know i did anything wrong? Where should the domain point to and are there additional configs i need to know about

**Comment by scriptburn** [comment]
Did you followed install instructions ?
can you tell me how did you install this ? 
Do you see .htaccess in public folder

**Comment by scriptburn** [comment]
I am closing this issue as i have not received any more follow up on this
