### ISSUE TITLE
Parse error after logon

### ISSUE THREAD

**Issue by andrekutianski** [scriptburn/git-auto-deploy#4]
`Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /home/devrede/deploy.dev.eunarede.com/app/src/Controllers/ProjectsController.php on line 27`

This happens after logon

**Comment by scriptburn** [comment]
Please update to php 7 and issue will be fixed

**Comment by scriptburn** [comment]
Main source of this error is use of a php protected keyword(list) being used as a class method in ProjectsController class, Which is acceptable in php 7 but not in version prior to that , First requirement of this package is that you must use php 7. But i did not enforced it in composer.json  which i just did 
But i would just prefer to avoid to use php protected word at all so renamed the ProjectsController:list function to ProjectsController:listAll
