### ISSUE TITLE
Hook is not working

### ISSUE THREAD

**Issue by wasiqaftab** [scriptburn/git-auto-deploy#6]
Hello

First to all thanks for this amazing script and lovely admin panel. I need to ask that i create ssh keys like you said make sudomain which have you system. Than i create post_hook.php in my project file as an example. But when i try to commit and push it didnt work every time shows me hook failed and no error log shows just content not fond

**Comment by wasiqaftab** [comment]
Hello

i just dig your code this line in service 
`if (isset($data['headers']['HTTP_USER_AGENT'][0]) && stripos($data['headers']['HTTP_USER_AGENT'][0], 'Go-http-client') !== false && isset($data['headers']['HTTP_X_GITLAB_EVENT'][0]))`

is not working gitlab is not giving http_user_agent and when i remove i got error on gitlab end any suggestion

**Comment by scriptburn** [comment]
HI,
sorry for getting back late,
Can you provide the error your are getting in gitlab end ?
as i tested it and gitlab provided me HTTP_USER_AGENT header

**Comment by wasiqaftab** [comment]
@scriptburn sorry for late reply if you see this
http://prntscr.com/gledxg
and these are my settings
http://prntscr.com/gleegh
Please help me in it

**Comment by xpablos** [comment]
Correct condition should by just:
if (isset($data['headers']['HTTP_X_GITLAB_EVENT'][0]))

I can confirm, that GitLab doesn't send HTTP_USER_AGENT headers. When I try print_r($data) in "identify" method, I am getting:

....
[headers] => Array
	(
		[CONTENT_TYPE] => Array
			(
				[0] => application/json
			)
		[HTTP_X_GITLAB_EVENT] => Array
			(
				[0] => Push Hook
			)
		[HTTP_X_GITLAB_TOKEN] => Array
			(
				[0] => ........
			)
		[HTTP_CONNECTION] => Array
			(
				[0] => close
			)
		[Host] => Array
			(
				[0] => .......
			)
		[CONTENT_LENGTH] => Array
			(
				[0] => 2523
			)
	)
.....

**Comment by scriptburn** [comment]
Please update to latest version , That should fix this issue

**Comment by wasiqaftab** [comment]
Thanks alot
