### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by pquerner** [scriptburn/git-auto-deploy#8]
Hey, nice app, but there are some things I dont get:

1.  What is pbcopy? Is it a MAC Only thing? What about ```ssh-copy-id -i ~/.ssh/mykey user@host``` which is almost default?
2.  Does this app has to be installed for each app for each domain? Or just 1 time on some server mydomain.com and if you want to deploy someappforcustomer.com you will still use mydomain.com to do the job?

Thanks!

**Comment by scriptburn** [comment]
1. pbcopy is mac command to copy content of a file to clipboard , yes it is MAC only thing sorry about that 
2.If each domain are on same physical server and if the user which runs the git-auto-deploy web process(user account of mydomain.com) has write access to those different domains (someappforcustomer.com etc) accounts single installation will work ,
